{% set version = "0.2.0" %}

package:
  name: oceanspy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/oceanspy/oceanspy-{{ version }}.tar.gz
  sha256: eb49493812641c0540b6474cc62075ea3f4db54412ecd0d0d9b1f3e102a334f8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
    - pytest
  run:
    - dask
    - python >=3.6
    - xarray
    - xgcm

test:
  imports:
    - oceanspy
  requires:
    - pytest

about:
  home: https://github.com/hainegroup/oceanspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for easy ocean model data analysis and visualization

extra:
  recipe-maintainers:
    - ocefpaf
    - malmans2
